### ISSUE TITLE
User Story: Browse products

### ISSUE THREAD

**Issue by Meyaal** [Meyaal/tea-house#14]
As a user **I want a product page** so that **I can browse available products**

### Approval Criteria

* Product page
* Products can be viewed

### Tasks
 

- [ ] Add Database model for products
- [ ] Build and Style product page
- [ ]  Add products to Database
- [ ] Add vie
- [ ]  Add url
- [ ] Comments
- [ ] Add new comment
- [ ] Markdown input: edit mode selected.
