### ISSUE TITLE
User Story: Filter products

### ISSUE THREAD

**Issue by Meyaal** [Meyaal/tea-house#16]
As a user **I want to be able to filter products** so that **I can view category-specific lists**

### Approval Criteria

* Can filter by price, category

### Tasks
 

- [ ] Add view
- [ ] Connect to navigation
- [ ] Comments
- [ ] Add new comment
- [ ] Markdown input: edit mode selected.
