### ISSUE TITLE
User Story: Add to bag

### ISSUE THREAD

**Issue by Meyaal** [Meyaal/tea-house#24]
As a user **I want a shopping bag** so that **I can add products to it**

### Approval Criteria

* User can add a product to the shopping bag

### Tasks
 

- [ ] Create the bag app
- [ ] Create the view
- [ ]  Create the template
