### ISSUE TITLE
User Story: Checkout securly

### ISSUE THREAD

**Issue by Meyaal** [Meyaal/tea-house#31]
As a user **I want to be able to checkout** and get **feedback so that I can buy things.**

### Approval Criteria
* Checkout works
* User gets feedback email
* User gets on site feedback

### Tasks
 
- [ ] Add checkout app
- [ ] Integrate Stripe
- [ ] Create messages on site
- [ ] Wire up email response
