### ISSUE TITLE
User Story: Blog post view

### ISSUE THREAD

**Issue by Meyaal** [Meyaal/tea-house#32]
As a user **I want a page that displays blog posts** so **that I can read them**

### Approval Criteria

* Page lists all blog posts

### Tasks
 

- [ ] Create an app for blog
- [ ] Create a view for view posts
- [ ] Create a model for this
- [ ] Create a template to render the posts to
