### ISSUE TITLE
User Story: Product admin

### ISSUE THREAD

**Issue by Meyaal** [Meyaal/tea-house#44]
As a admin **I want edit,delete and upload form** so that **I can manage products**

### Approval Criteria

-  Can add
- Edit
- and delete products without logging into Django admin

### Tasks
 

- [ ] Create an edit page
- [ ]  Create a delete button
- [ ]  Create an upload page
