### ISSUE TITLE
User Story: Create an account 

### ISSUE THREAD

**Issue by Meyaal** [Meyaal/tea-house#8]
As a new user **I can register for the website** so that **I can hold an account**

## Approval Criteria

* User can create an account

### Tasks

- [ ] Set up allauth
- [ ]  Create a signup page
- [ ] Style the UI
